package mc.xesau.bukkitutils.configutils;

import java.util.HashMap;

import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class ConfigItemStack {

	/**
	 * The ItemStack that will be generated from a
	 * {@link org.bukkit.configuration.ConfigurationSection}
	 */
	private ItemStack stack;

	/**
	 * Create a ConfigItemStack instance from a
	 * {@link org.bukkit.configuration.ConfigurationSection}
	 * 
	 * @param ref
	 *            The ConfigurationSection itself.
	 */
	public ConfigItemStack(ConfigurationSection ref) {
		ItemStack temp = new ItemStack(Material.getMaterial(ref
				.getString("type")), Short.parseShort(ref.getString("amount")),
				Byte.parseByte(ref.getString("damage")));

		ItemMeta tempMeta = temp.getItemMeta();

		tempMeta.setDisplayName(ref.getString("metadata.displayname"));
		tempMeta.setLore(ref.getStringList("metadata.lore"));

		ConfigurationSection enchantments = ref
				.getConfigurationSection("metadata.enchantments");

		for (String enchantment : enchantments.getKeys(false)) {
			tempMeta.addEnchant(Enchantment.getByName(enchantment),
					enchantments.getInt(enchantment), true);
		}

		temp.setItemMeta(tempMeta);
		stack = temp;
	}

	/**
	 * Create a ConfigItemStack from a ItemStack
	 * 
	 * @param stack
	 *            The ItemStack
	 */
	public ConfigItemStack(ItemStack stack) {
		this.stack = stack;
	}

	/**
	 * Get the ItemStack generated by the
	 * {@link org.bukkit.configuration.ConfigurationSection}
	 * 
	 * @return the generated {@link org.bukkit.inventory.ItemStack}
	 */
	public ItemStack getItemStack() {
		return stack;
	}

	/**
	 * Set the ItemStack
	 * 
	 * @param stack
	 *            The ItemStack to set
	 * 
	 * @return The ConfigItemStack instance as builder, to use
	 *         .getConfigurationMap();
	 */
	public ConfigItemStack setItemStack(ItemStack stack) {
		this.stack = stack;
		return this;
	}

	/**
	 * Generate a HashMap that contains the data of the ItemStack, and can be
	 * set with
	 * {@link org.bukkit.configuration.ConfigurationSection#set(String,Object)},
	 * because Maps are stored as ConfigurationSections
	 * 
	 * @return The HashMap with data
	 */
	public HashMap<String, Object> getConfigurationMap() {
		HashMap<String, Object> itemMap = new HashMap<String, Object>();
		itemMap.put("type", stack.getType().toString());
		itemMap.put("damage", stack.getDurability());
		itemMap.put("amount", stack.getAmount());

		ItemMeta meta = stack.getItemMeta();

		HashMap<String, Object> metaMap = new HashMap<String, Object>();
		metaMap.put("displayname", meta.getDisplayName());
		metaMap.put("lore", meta.getLore());
		metaMap.put("enchantments", meta.getEnchants());

		itemMap.put("metadata", metaMap);

		return itemMap;
	}

}
